
import type { Country, Category, Article } from './types';

export const countries: Country[] = [
  { code: 'AF', name: 'Afghanistan', flagUrl: 'https://flagcdn.com/w320/af.png', nativeLanguageName: 'Pashto/Dari', nativeLanguageCode: 'ps' },
  { code: 'AL', name: 'Albania', flagUrl: 'https://flagcdn.com/w320/al.png', nativeLanguageName: 'Shqip', nativeLanguageCode: 'sq' },
  { code: 'DZ', name: 'Algeria', flagUrl: 'https://flagcdn.com/w320/dz.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'AD', name: 'Andorra', flagUrl: 'https://flagcdn.com/w320/ad.png', nativeLanguageName: 'Català', nativeLanguageCode: 'ca' },
  { code: 'AO', name: 'Angola', flagUrl: 'https://flagcdn.com/w320/ao.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'AG', name: 'Antigua and Barbuda', flagUrl: 'https://flagcdn.com/w320/ag.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'AR', name: 'Argentina', flagUrl: 'https://flagcdn.com/w320/ar.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'AM', name: 'Armenia', flagUrl: 'https://flagcdn.com/w320/am.png', nativeLanguageName: 'Հայերեն', nativeLanguageCode: 'hy' },
  { code: 'AU', name: 'Australia', flagUrl: 'https://flagcdn.com/w320/au.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'AT', name: 'Austria', flagUrl: 'https://flagcdn.com/w320/at.png', nativeLanguageName: 'Deutsch', nativeLanguageCode: 'de' },
  { code: 'AZ', name: 'Azerbaijan', flagUrl: 'https://flagcdn.com/w320/az.png', nativeLanguageName: 'Azərbaycan dili', nativeLanguageCode: 'az' },
  { code: 'BS', name: 'Bahamas', flagUrl: 'https://flagcdn.com/w320/bs.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'BH', name: 'Bahrain', flagUrl: 'https://flagcdn.com/w320/bh.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'BD', name: 'Bangladesh', flagUrl: 'https://flagcdn.com/w320/bd.png', nativeLanguageName: 'বাংলা', nativeLanguageCode: 'bn_country' },
  { code: 'BB', name: 'Barbados', flagUrl: 'https://flagcdn.com/w320/bb.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'BY', name: 'Belarus', flagUrl: 'https://flagcdn.com/w320/by.png', nativeLanguageName: 'Беларуская', nativeLanguageCode: 'be' },
  { code: 'BE', name: 'Belgium', flagUrl: 'https://flagcdn.com/w320/be.png', nativeLanguageName: 'Nederlands/Français/Deutsch', nativeLanguageCode: 'nl' },
  { code: 'BZ', name: 'Belize', flagUrl: 'https://flagcdn.com/w320/bz.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'BJ', name: 'Benin', flagUrl: 'https://flagcdn.com/w320/bj.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'BT', name: 'Bhutan', flagUrl: 'https://flagcdn.com/w320/bt.png', nativeLanguageName: 'རྫོང་ཁ', nativeLanguageCode: 'dz' },
  { code: 'BO', name: 'Bolivia', flagUrl: 'https://flagcdn.com/w320/bo.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'BA', name: 'Bosnia and Herzegovina', flagUrl: 'https://flagcdn.com/w320/ba.png', nativeLanguageName: 'Bosanski/Hrvatski/Srpski', nativeLanguageCode: 'bs' },
  { code: 'BW', name: 'Botswana', flagUrl: 'https://flagcdn.com/w320/bw.png', nativeLanguageName: 'Setswana/English', nativeLanguageCode: 'tn' },
  { code: 'BR', name: 'Brazil', flagUrl: 'https://flagcdn.com/w320/br.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'BN', name: 'Brunei', flagUrl: 'https://flagcdn.com/w320/bn.png', nativeLanguageName: 'Bahasa Melayu', nativeLanguageCode: 'ms' },
  { code: 'BG', name: 'Bulgaria', flagUrl: 'https://flagcdn.com/w320/bg.png', nativeLanguageName: 'Български', nativeLanguageCode: 'bg' },
  { code: 'BF', name: 'Burkina Faso', flagUrl: 'https://flagcdn.com/w320/bf.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'BI', name: 'Burundi', flagUrl: 'https://flagcdn.com/w320/bi.png', nativeLanguageName: 'Kirundi/Français', nativeLanguageCode: 'rn' },
  { code: 'CV', name: 'Cabo Verde', flagUrl: 'https://flagcdn.com/w320/cv.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'KH', name: 'Cambodia', flagUrl: 'https://flagcdn.com/w320/kh.png', nativeLanguageName: 'ភាសាខ្មែរ', nativeLanguageCode: 'km' },
  { code: 'CM', name: 'Cameroon', flagUrl: 'https://flagcdn.com/w320/cm.png', nativeLanguageName: 'Français/English', nativeLanguageCode: 'fr' },
  { code: 'CA', name: 'Canada', flagUrl: 'https://flagcdn.com/w320/ca.png', nativeLanguageName: 'English/Français', nativeLanguageCode: 'en' },
  { code: 'CF', name: 'Central African Republic', flagUrl: 'https://flagcdn.com/w320/cf.png', nativeLanguageName: 'Français/Sango', nativeLanguageCode: 'fr' },
  { code: 'TD', name: 'Chad', flagUrl: 'https://flagcdn.com/w320/td.png', nativeLanguageName: 'Français/العربية', nativeLanguageCode: 'fr' },
  { code: 'CL', name: 'Chile', flagUrl: 'https://flagcdn.com/w320/cl.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'CN', name: 'China', flagUrl: 'https://flagcdn.com/w320/cn.png', nativeLanguageName: '中文', nativeLanguageCode: 'zh' },
  { code: 'CO', name: 'Colombia', flagUrl: 'https://flagcdn.com/w320/co.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'KM', name: 'Comoros', flagUrl: 'https://flagcdn.com/w320/km.png', nativeLanguageName: 'Français/العربية/Shikomori', nativeLanguageCode: 'fr' },
  { code: 'CG', name: 'Congo (Congo-Brazzaville)', flagUrl: 'https://flagcdn.com/w320/cg.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'CR', name: 'Costa Rica', flagUrl: 'https://flagcdn.com/w320/cr.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'HR', name: 'Croatia', flagUrl: 'https://flagcdn.com/w320/hr.png', nativeLanguageName: 'Hrvatski', nativeLanguageCode: 'hr' },
  { code: 'CU', name: 'Cuba', flagUrl: 'https://flagcdn.com/w320/cu.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'CY', name: 'Cyprus', flagUrl: 'https://flagcdn.com/w320/cy.png', nativeLanguageName: 'Ελληνικά/Türkçe', nativeLanguageCode: 'el' },
  { code: 'CZ', name: 'Czech Republic', flagUrl: 'https://flagcdn.com/w320/cz.png', nativeLanguageName: 'Čeština', nativeLanguageCode: 'cs' },
  { code: 'CD', name: 'DR Congo', flagUrl: 'https://flagcdn.com/w320/cd.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'DK', name: 'Denmark', flagUrl: 'https://flagcdn.com/w320/dk.png', nativeLanguageName: 'Dansk', nativeLanguageCode: 'da' },
  { code: 'DJ', name: 'Djibouti', flagUrl: 'https://flagcdn.com/w320/dj.png', nativeLanguageName: 'Français/العربية', nativeLanguageCode: 'fr' },
  { code: 'DM', name: 'Dominica', flagUrl: 'https://flagcdn.com/w320/dm.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'DO', name: 'Dominican Republic', flagUrl: 'https://flagcdn.com/w320/do.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'EC', name: 'Ecuador', flagUrl: 'https://flagcdn.com/w320/ec.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'EG', name: 'Egypt', flagUrl: 'https://flagcdn.com/w320/eg.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'SV', name: 'El Salvador', flagUrl: 'https://flagcdn.com/w320/sv.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'GQ', name: 'Equatorial Guinea', flagUrl: 'https://flagcdn.com/w320/gq.png', nativeLanguageName: 'Español/Français/Português', nativeLanguageCode: 'es' },
  { code: 'ER', name: 'Eritrea', flagUrl: 'https://flagcdn.com/w320/er.png', nativeLanguageName: 'ትግርኛ/العربية/English', nativeLanguageCode: 'ti' },
  { code: 'EE', name: 'Estonia', flagUrl: 'https://flagcdn.com/w320/ee.png', nativeLanguageName: 'Eesti', nativeLanguageCode: 'et' },
  { code: 'SZ', name: 'Eswatini', flagUrl: 'https://flagcdn.com/w320/sz.png', nativeLanguageName: 'siSwati/English', nativeLanguageCode: 'ss' },
  { code: 'ET', name: 'Ethiopia', flagUrl: 'https://flagcdn.com/w320/et.png', nativeLanguageName: 'አማርኛ', nativeLanguageCode: 'am' },
  { code: 'FJ', name: 'Fiji', flagUrl: 'https://flagcdn.com/w320/fj.png', nativeLanguageName: 'English/Fijian/Hindi', nativeLanguageCode: 'en' },
  { code: 'FI', name: 'Finland', flagUrl: 'https://flagcdn.com/w320/fi.png', nativeLanguageName: 'Suomi/Svenska', nativeLanguageCode: 'fi' },
  { code: 'FR', name: 'France', flagUrl: 'https://flagcdn.com/w320/fr.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'GA', name: 'Gabon', flagUrl: 'https://flagcdn.com/w320/ga.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'GM', name: 'Gambia', flagUrl: 'https://flagcdn.com/w320/gm.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'GE', name: 'Georgia', flagUrl: 'https://flagcdn.com/w320/ge.png', nativeLanguageName: 'ქართული', nativeLanguageCode: 'ka' },
  { code: 'DE', name: 'Germany', flagUrl: 'https://flagcdn.com/w320/de.png', nativeLanguageName: 'Deutsch', nativeLanguageCode: 'de' },
  { code: 'GH', name: 'Ghana', flagUrl: 'https://flagcdn.com/w320/gh.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'GR', name: 'Greece', flagUrl: 'https://flagcdn.com/w320/gr.png', nativeLanguageName: 'Ελληνικά', nativeLanguageCode: 'el' },
  { code: 'GD', name: 'Grenada', flagUrl: 'https://flagcdn.com/w320/gd.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'GT', name: 'Guatemala', flagUrl: 'https://flagcdn.com/w320/gt.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'GN', name: 'Guinea', flagUrl: 'https://flagcdn.com/w320/gn.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'GW', name: 'Guinea-Bissau', flagUrl: 'https://flagcdn.com/w320/gw.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'GY', name: 'Guyana', flagUrl: 'https://flagcdn.com/w320/gy.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'HT', name: 'Haiti', flagUrl: 'https://flagcdn.com/w320/ht.png', nativeLanguageName: 'Français/Kreyòl ayisyen', nativeLanguageCode: 'fr' },
  { code: 'HN', name: 'Honduras', flagUrl: 'https://flagcdn.com/w320/hn.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'HU', name: 'Hungary', flagUrl: 'https://flagcdn.com/w320/hu.png', nativeLanguageName: 'Magyar', nativeLanguageCode: 'hu' },
  { code: 'IS', name: 'Iceland', flagUrl: 'https://flagcdn.com/w320/is.png', nativeLanguageName: 'Íslenska', nativeLanguageCode: 'is' },
  { code: 'IN', name: 'India', flagUrl: 'https://flagcdn.com/w320/in.png', nativeLanguageName: 'हिन्दी', nativeLanguageCode: 'hi' },
  { code: 'ID', name: 'Indonesia', flagUrl: 'https://flagcdn.com/w320/id.png', nativeLanguageName: 'Bahasa Indonesia', nativeLanguageCode: 'id' },
  { code: 'IR', name: 'Iran', flagUrl: 'https://flagcdn.com/w320/ir.png', nativeLanguageName: 'فارسی', nativeLanguageCode: 'fa' },
  { code: 'IQ', name: 'Iraq', flagUrl: 'https://flagcdn.com/w320/iq.png', nativeLanguageName: 'العربية/کوردی', nativeLanguageCode: 'ar' },
  { code: 'IE', name: 'Ireland', flagUrl: 'https://flagcdn.com/w320/ie.png', nativeLanguageName: 'English/Gaeilge', nativeLanguageCode: 'en' },
  { code: 'IL', name: 'Israel', flagUrl: 'https://flagcdn.com/w320/il.png', nativeLanguageName: 'עברית/العربية', nativeLanguageCode: 'he' },
  { code: 'IT', name: 'Italy', flagUrl: 'https://flagcdn.com/w320/it.png', nativeLanguageName: 'Italiano', nativeLanguageCode: 'it' },
  { code: 'JM', name: 'Jamaica', flagUrl: 'https://flagcdn.com/w320/jm.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'JP', name: 'Japan', flagUrl: 'https://flagcdn.com/w320/jp.png', nativeLanguageName: '日本語', nativeLanguageCode: 'ja' },
  { code: 'JO', name: 'Jordan', flagUrl: 'https://flagcdn.com/w320/jo.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'KZ', name: 'Kazakhstan', flagUrl: 'https://flagcdn.com/w320/kz.png', nativeLanguageName: 'Қазақ тілі/Русский', nativeLanguageCode: 'kk' },
  { code: 'KE', name: 'Kenya', flagUrl: 'https://flagcdn.com/w320/ke.png', nativeLanguageName: 'Swahili/English', nativeLanguageCode: 'sw' },
  { code: 'KI', name: 'Kiribati', flagUrl: 'https://flagcdn.com/w320/ki.png', nativeLanguageName: 'English/Gilbertese', nativeLanguageCode: 'en' },
  { code: 'XK', name: 'Kosovo', flagUrl: 'https://flagcdn.com/w320/xk.png', nativeLanguageName: 'Shqip/Srpski', nativeLanguageCode: 'sq' },
  { code: 'KW', name: 'Kuwait', flagUrl: 'https://flagcdn.com/w320/kw.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'KG', name: 'Kyrgyzstan', flagUrl: 'https://flagcdn.com/w320/kg.png', nativeLanguageName: 'Кыргызча/Русский', nativeLanguageCode: 'ky' },
  { code: 'LA', name: 'Laos', flagUrl: 'https://flagcdn.com/w320/la.png', nativeLanguageName: 'ພາສາລາວ', nativeLanguageCode: 'lo' },
  { code: 'LV', name: 'Latvia', flagUrl: 'https://flagcdn.com/w320/lv.png', nativeLanguageName: 'Latviešu', nativeLanguageCode: 'lv' },
  { code: 'LB', name: 'Lebanon', flagUrl: 'https://flagcdn.com/w320/lb.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'LS', name: 'Lesotho', flagUrl: 'https://flagcdn.com/w320/ls.png', nativeLanguageName: 'Sesotho/English', nativeLanguageCode: 'st' },
  { code: 'LR', name: 'Liberia', flagUrl: 'https://flagcdn.com/w320/lr.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'LY', name: 'Libya', flagUrl: 'https://flagcdn.com/w320/ly.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'LI', name: 'Liechtenstein', flagUrl: 'https://flagcdn.com/w320/li.png', nativeLanguageName: 'Deutsch', nativeLanguageCode: 'de' },
  { code: 'LT', name: 'Lithuania', flagUrl: 'https://flagcdn.com/w320/lt.png', nativeLanguageName: 'Lietuvių', nativeLanguageCode: 'lt' },
  { code: 'LU', name: 'Luxembourg', flagUrl: 'https://flagcdn.com/w320/lu.png', nativeLanguageName: 'Lëtzebuergesch/Français/Deutsch', nativeLanguageCode: 'lb' },
  { code: 'MG', name: 'Madagascar', flagUrl: 'https://flagcdn.com/w320/mg.png', nativeLanguageName: 'Malagasy/Français', nativeLanguageCode: 'mg' },
  { code: 'MW', name: 'Malawi', flagUrl: 'https://flagcdn.com/w320/mw.png', nativeLanguageName: 'Chichewa/English', nativeLanguageCode: 'ny' },
  { code: 'MY', name: 'Malaysia', flagUrl: 'https://flagcdn.com/w320/my.png', nativeLanguageName: 'Bahasa Malaysia', nativeLanguageCode: 'ms' },
  { code: 'MV', name: 'Maldives', flagUrl: 'https://flagcdn.com/w320/mv.png', nativeLanguageName: 'ދިވެހިބަސް', nativeLanguageCode: 'dv' },
  { code: 'ML', name: 'Mali', flagUrl: 'https://flagcdn.com/w320/ml.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'MT', name: 'Malta', flagUrl: 'https://flagcdn.com/w320/mt.png', nativeLanguageName: 'Malti/English', nativeLanguageCode: 'mt' },
  { code: 'MH', name: 'Marshall Islands', flagUrl: 'https://flagcdn.com/w320/mh.png', nativeLanguageName: 'English/Marshallese', nativeLanguageCode: 'en' },
  { code: 'MR', name: 'Mauritania', flagUrl: 'https://flagcdn.com/w320/mr.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'MU', name: 'Mauritius', flagUrl: 'https://flagcdn.com/w320/mu.png', nativeLanguageName: 'English/Français', nativeLanguageCode: 'en' },
  { code: 'MX', name: 'Mexico', flagUrl: 'https://flagcdn.com/w320/mx.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'FM', name: 'Micronesia', flagUrl: 'https://flagcdn.com/w320/fm.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'MD', name: 'Moldova', flagUrl: 'https://flagcdn.com/w320/md.png', nativeLanguageName: 'Română', nativeLanguageCode: 'ro' },
  { code: 'MC', name: 'Monaco', flagUrl: 'https://flagcdn.com/w320/mc.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'MN', name: 'Mongolia', flagUrl: 'https://flagcdn.com/w320/mn.png', nativeLanguageName: 'Монгол', nativeLanguageCode: 'mn' },
  { code: 'ME', name: 'Montenegro', flagUrl: 'https://flagcdn.com/w320/me.png', nativeLanguageName: 'Crnogorski', nativeLanguageCode: 'sr' },
  { code: 'MA', name: 'Morocco', flagUrl: 'https://flagcdn.com/w320/ma.png', nativeLanguageName: 'العربية/Amazigh', nativeLanguageCode: 'ar' },
  { code: 'MZ', name: 'Mozambique', flagUrl: 'https://flagcdn.com/w320/mz.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'MM', name: 'Myanmar', flagUrl: 'https://flagcdn.com/w320/mm.png', nativeLanguageName: 'မြန်မာဘာသာ', nativeLanguageCode: 'my' },
  { code: 'NA', name: 'Namibia', flagUrl: 'https://flagcdn.com/w320/na.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'NR', name: 'Nauru', flagUrl: 'https://flagcdn.com/w320/nr.png', nativeLanguageName: 'Nauruan/English', nativeLanguageCode: 'na' },
  { code: 'NP', name: 'Nepal', flagUrl: 'https://flagcdn.com/w320/np.png', nativeLanguageName: 'नेपाली', nativeLanguageCode: 'ne' },
  { code: 'NL', name: 'Netherlands', flagUrl: 'https://flagcdn.com/w320/nl.png', nativeLanguageName: 'Nederlands', nativeLanguageCode: 'nl' },
  { code: 'NZ', name: 'New Zealand', flagUrl: 'https://flagcdn.com/w320/nz.png', nativeLanguageName: 'English/Māori', nativeLanguageCode: 'en' },
  { code: 'NI', name: 'Nicaragua', flagUrl: 'https://flagcdn.com/w320/ni.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'NE', name: 'Niger', flagUrl: 'https://flagcdn.com/w320/ne.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'NG', name: 'Nigeria', flagUrl: 'https://flagcdn.com/w320/ng.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'KP', name: 'North Korea', flagUrl: 'https://flagcdn.com/w320/kp.png', nativeLanguageName: '한국어', nativeLanguageCode: 'ko' },
  { code: 'MK', name: 'North Macedonia', flagUrl: 'https://flagcdn.com/w320/mk.png', nativeLanguageName: 'Македонски', nativeLanguageCode: 'mk' },
  { code: 'NO', name: 'Norway', flagUrl: 'https://flagcdn.com/w320/no.png', nativeLanguageName: 'Norsk', nativeLanguageCode: 'no' },
  { code: 'OM', name: 'Oman', flagUrl: 'https://flagcdn.com/w320/om.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'PK', name: 'Pakistan', flagUrl: 'https://flagcdn.com/w320/pk.png', nativeLanguageName: 'اردو/English', nativeLanguageCode: 'ur' },
  { code: 'PW', name: 'Palau', flagUrl: 'https://flagcdn.com/w320/pw.png', nativeLanguageName: 'Palauan/English', nativeLanguageCode: 'pau' },
  { code: 'PS', name: 'Palestine State', flagUrl: 'https://flagcdn.com/w320/ps.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'PA', name: 'Panama', flagUrl: 'https://flagcdn.com/w320/pa.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'PG', name: 'Papua New Guinea', flagUrl: 'https://flagcdn.com/w320/pg.png', nativeLanguageName: 'English/Tok Pisin/Hiri Motu', nativeLanguageCode: 'en' },
  { code: 'PY', name: 'Paraguay', flagUrl: 'https://flagcdn.com/w320/py.png', nativeLanguageName: 'Español/Guaraní', nativeLanguageCode: 'es' },
  { code: 'PE', name: 'Peru', flagUrl: 'https://flagcdn.com/w320/pe.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'PH', name: 'Philippines', flagUrl: 'https://flagcdn.com/w320/ph.png', nativeLanguageName: 'Filipino/English', nativeLanguageCode: 'tl' },
  { code: 'PL', name: 'Poland', flagUrl: 'https://flagcdn.com/w320/pl.png', nativeLanguageName: 'Polski', nativeLanguageCode: 'pl' },
  { code: 'PT', name: 'Portugal', flagUrl: 'https://flagcdn.com/w320/pt.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'QA', name: 'Qatar', flagUrl: 'https://flagcdn.com/w320/qa.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'RO', name: 'Romania', flagUrl: 'https://flagcdn.com/w320/ro.png', nativeLanguageName: 'Română', nativeLanguageCode: 'ro' },
  { code: 'RU', name: 'Russia', flagUrl: 'https://flagcdn.com/w320/ru.png', nativeLanguageName: 'Русский', nativeLanguageCode: 'ru' },
  { code: 'RW', name: 'Rwanda', flagUrl: 'https://flagcdn.com/w320/rw.png', nativeLanguageName: 'Kinyarwanda/Français/English', nativeLanguageCode: 'rw' },
  { code: 'KN', name: 'Saint Kitts and Nevis', flagUrl: 'https://flagcdn.com/w320/kn.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'LC', name: 'Saint Lucia', flagUrl: 'https://flagcdn.com/w320/lc.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'VC', name: 'Saint Vincent and the Grenadines', flagUrl: 'https://flagcdn.com/w320/vc.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'WS', name: 'Samoa', flagUrl: 'https://flagcdn.com/w320/ws.png', nativeLanguageName: 'Samoan/English', nativeLanguageCode: 'sm' },
  { code: 'SM', name: 'San Marino', flagUrl: 'https://flagcdn.com/w320/sm.png', nativeLanguageName: 'Italiano', nativeLanguageCode: 'it' },
  { code: 'ST', name: 'Sao Tome and Principe', flagUrl: 'https://flagcdn.com/w320/st.png', nativeLanguageName: 'Português', nativeLanguageCode: 'pt' },
  { code: 'SA', name: 'Saudi Arabia', flagUrl: 'https://flagcdn.com/w320/sa.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'SN', name: 'Senegal', flagUrl: 'https://flagcdn.com/w320/sn.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'RS', name: 'Serbia', flagUrl: 'https://flagcdn.com/w320/rs.png', nativeLanguageName: 'Српски', nativeLanguageCode: 'sr' },
  { code: 'SC', name: 'Seychelles', flagUrl: 'https://flagcdn.com/w320/sc.png', nativeLanguageName: 'Seychellois Creole/English/Français', nativeLanguageCode: 'fr' },
  { code: 'SL', name: 'Sierra Leone', flagUrl: 'https://flagcdn.com/w320/sl.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'SG', name: 'Singapore', flagUrl: 'https://flagcdn.com/w320/sg.png', nativeLanguageName: 'English/Malay/Mandarin/Tamil', nativeLanguageCode: 'en' },
  { code: 'SK', name: 'Slovakia', flagUrl: 'https://flagcdn.com/w320/sk.png', nativeLanguageName: 'Slovenčina', nativeLanguageCode: 'sk' },
  { code: 'SI', name: 'Slovenia', flagUrl: 'https://flagcdn.com/w320/si.png', nativeLanguageName: 'Slovenščina', nativeLanguageCode: 'sl' },
  { code: 'SB', name: 'Solomon Islands', flagUrl: 'https://flagcdn.com/w320/sb.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'SO', name: 'Somalia', flagUrl: 'https://flagcdn.com/w320/so.png', nativeLanguageName: 'Soomaali/العربية', nativeLanguageCode: 'so' },
  { code: 'ZA', name: 'South Africa', flagUrl: 'https://flagcdn.com/w320/za.png', nativeLanguageName: 'Multiple (English, Zulu, Xhosa, Afrikaans, etc.)', nativeLanguageCode: 'en' },
  { code: 'KR', name: 'South Korea', flagUrl: 'https://flagcdn.com/w320/kr.png', nativeLanguageName: '한국어', nativeLanguageCode: 'ko' },
  { code: 'SS', name: 'South Sudan', flagUrl: 'https://flagcdn.com/w320/ss.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'ES', name: 'Spain', flagUrl: 'https://flagcdn.com/w320/es.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'LK', name: 'Sri Lanka', flagUrl: 'https://flagcdn.com/w320/lk.png', nativeLanguageName: 'සිංහල/தமிழ்', nativeLanguageCode: 'si' },
  { code: 'SD', name: 'Sudan', flagUrl: 'https://flagcdn.com/w320/sd.png', nativeLanguageName: 'العربية/English', nativeLanguageCode: 'ar' },
  { code: 'SR', name: 'Suriname', flagUrl: 'https://flagcdn.com/w320/sr.png', nativeLanguageName: 'Nederlands', nativeLanguageCode: 'nl' },
  { code: 'SE', name: 'Sweden', flagUrl: 'https://flagcdn.com/w320/se.png', nativeLanguageName: 'Svenska', nativeLanguageCode: 'sv' },
  { code: 'CH', name: 'Switzerland', flagUrl: 'https://flagcdn.com/w320/ch.png', nativeLanguageName: 'Deutsch/Français/Italiano', nativeLanguageCode: 'de' },
  { code: 'SY', name: 'Syria', flagUrl: 'https://flagcdn.com/w320/sy.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'TW', name: 'Taiwan', flagUrl: 'https://flagcdn.com/w320/tw.png', nativeLanguageName: '中文 (繁體)', nativeLanguageCode: 'zh' },
  { code: 'TJ', name: 'Tajikistan', flagUrl: 'https://flagcdn.com/w320/tj.png', nativeLanguageName: 'Тоҷикӣ', nativeLanguageCode: 'tg' },
  { code: 'TZ', name: 'Tanzania', flagUrl: 'https://flagcdn.com/w320/tz.png', nativeLanguageName: 'Swahili/English', nativeLanguageCode: 'sw' },
  { code: 'TH', name: 'Thailand', flagUrl: 'https://flagcdn.com/w320/th.png', nativeLanguageName: 'ภาษาไทย', nativeLanguageCode: 'th' },
  { code: 'TL', name: 'Timor-Leste', flagUrl: 'https://flagcdn.com/w320/tl.png', nativeLanguageName: 'Tetun/Português', nativeLanguageCode: 'tet' },
  { code: 'TG', name: 'Togo', flagUrl: 'https://flagcdn.com/w320/tg.png', nativeLanguageName: 'Français', nativeLanguageCode: 'fr' },
  { code: 'TO', name: 'Tonga', flagUrl: 'https://flagcdn.com/w320/to.png', nativeLanguageName: 'Tongan/English', nativeLanguageCode: 'to' },
  { code: 'TT', name: 'Trinidad and Tobago', flagUrl: 'https://flagcdn.com/w320/tt.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'TN', name: 'Tunisia', flagUrl: 'https://flagcdn.com/w320/tn.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'TR', name: 'Turkey', flagUrl: 'https://flagcdn.com/w320/tr.png', nativeLanguageName: 'Türkçe', nativeLanguageCode: 'tr' },
  { code: 'TM', name: 'Turkmenistan', flagUrl: 'https://flagcdn.com/w320/tm.png', nativeLanguageName: 'Türkmençe', nativeLanguageCode: 'tk' },
  { code: 'TV', name: 'Tuvalu', flagUrl: 'https://flagcdn.com/w320/tv.png', nativeLanguageName: 'Tuvaluan/English', nativeLanguageCode: 'tvl' },
  { code: 'UG', name: 'Uganda', flagUrl: 'https://flagcdn.com/w320/ug.png', nativeLanguageName: 'English/Swahili', nativeLanguageCode: 'en' },
  { code: 'UA', name: 'Ukraine', flagUrl: 'https://flagcdn.com/w320/ua.png', nativeLanguageName: 'Українська', nativeLanguageCode: 'uk' },
  { code: 'AE', name: 'United Arab Emirates', flagUrl: 'https://flagcdn.com/w320/ae.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'GB', name: 'United Kingdom', flagUrl: 'https://flagcdn.com/w320/gb.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'US', name: 'United States', flagUrl: 'https://flagcdn.com/w320/us.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'UY', name: 'Uruguay', flagUrl: 'https://flagcdn.com/w320/uy.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'UZ', name: 'Uzbekistan', flagUrl: 'https://flagcdn.com/w320/uz.png', nativeLanguageName: 'Oʻzbekcha', nativeLanguageCode: 'uz' },
  { code: 'VU', name: 'Vanuatu', flagUrl: 'https://flagcdn.com/w320/vu.png', nativeLanguageName: 'Bislama/English/Français', nativeLanguageCode: 'bi' },
  { code: 'VA', name: 'Vatican City', flagUrl: 'https://flagcdn.com/w320/va.png', nativeLanguageName: 'Italiano/Latin', nativeLanguageCode: 'it' },
  { code: 'VE', name: 'Venezuela', flagUrl: 'https://flagcdn.com/w320/ve.png', nativeLanguageName: 'Español', nativeLanguageCode: 'es' },
  { code: 'VN', name: 'Vietnam', flagUrl: 'https://flagcdn.com/w320/vn.png', nativeLanguageName: 'Tiếng Việt', nativeLanguageCode: 'vi' },
  { code: 'EH', name: 'Western Sahara', flagUrl: 'https://flagcdn.com/w320/eh.png', nativeLanguageName: 'العربية/Español', nativeLanguageCode: 'ar' },
  { code: 'YE', name: 'Yemen', flagUrl: 'https://flagcdn.com/w320/ye.png', nativeLanguageName: 'العربية', nativeLanguageCode: 'ar' },
  { code: 'ZM', name: 'Zambia', flagUrl: 'https://flagcdn.com/w320/zm.png', nativeLanguageName: 'English', nativeLanguageCode: 'en' },
  { code: 'ZW', name: 'Zimbabwe', flagUrl: 'https://flagcdn.com/w320/zw.png', nativeLanguageName: 'English/Shona/Ndebele', nativeLanguageCode: 'en' },
];

export const categories: Category[] = [
  { id: 'tech', name: 'Technology' },
  { id: 'sports', name: 'Sports' },
  { id: 'politics', name: 'Politics' },
  { id: 'business', name: 'Business' },
  { id: 'world', name: 'World' },
  { id: 'science', name: 'Science' },
  { id: 'health', name: 'Health' },
  { id: 'entertainment', name: 'Entertainment' },
  { id: 'general', name: 'General'},
];

export const articles: Article[] = [
  {
    id: 'us-tech-1',
    countryCode: 'US',
    headline: 'New AI Chip Unveiled, Promising 10x Performance',
    summaries: {
      en: 'A leading tech company today announced a revolutionary AI chip that boasts a tenfold increase in processing power for complex machine learning tasks.',
      bn: 'একটি শীর্ষস্থানীয় প্রযুক্তি কোম্পানি আজ একটি বিপ্লবী এআই চিপ উন্মোচন করেছে যা জটিল মেশিন লার্নিং কাজের জন্য দশগুণ প্রক্রিয়াকরণ ক্ষমতা বৃদ্ধি করবে।',
    },
    source: 'TechChronicle',
    category: 'Technology',
    publishedDate: '2024-07-28T10:00:00Z',
    originalImageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'jp-sports-1',
    countryCode: 'JP',
    headline: 'Sumo Grand Champion Retains Title in Thrilling Final',
    summaries: {
      en: 'The reigning Sumo Grand Champion successfully defended his title in a nail-biting final match that captivated the nation.',
      bn: 'বর্তমান সুমো গ্র্যান্ড চ্যাম্পিয়ন একটি রুদ্ধশ্বাস ফাইনাল ম্যাচে তার শিরোপা সফলভাবে রক্ষা করেছেন যা পুরো জাতিকে মুগ্ধ করেছে।',
      ja: '現役の相撲グランドチャンピオンは、国中を魅了した手に汗握る決勝戦でタイトルを防衛しました。',
    },
    source: 'Japan Sports Today',
    category: 'Sports',
    publishedDate: '2024-07-28T14:30:00Z',
  },
  {
    id: 'bd-politics-1',
    countryCode: 'BD',
    headline: 'Parliament Passes New Environmental Protection Bill',
    summaries: {
      en: 'The national parliament has passed a new bill aimed at strengthening environmental protection measures across the country.',
      bn: 'জাতীয় সংসদ সারাদেশে পরিবেশ সুরক্ষা ব্যবস্থা জোরদার করার লক্ষ্যে একটি নতুন বিল পাস করেছে।',
      bn_country: 'জাতীয় সংসদ সারাদেশে পরিবেশ সুরক্ষা ব্যবস্থা জোরদার করার লক্ষ্যে একটি নতুন বিল পাস করেছে।',
    },
    source: 'Dhaka Times',
    category: 'Politics',
    publishedDate: '2024-07-27T09:15:00Z',
    originalImageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'gb-business-1',
    countryCode: 'GB',
    headline: 'UK Tech Startups Secure Record Funding in Q2',
    summaries: {
      en: 'British technology startups have attracted a record amount of investment in the second quarter, signaling a resilient innovation sector.',
      bn: 'ব্রিটিশ প্রযুক্তি স্টার্টআপগুলি দ্বিতীয় প্রান্তিকে রেকর্ড পরিমাণ বিনিয়োগ আকর্ষণ করেছে, যা একটি স্থিতিশীল উদ্ভাবনী খাতের ইঙ্গিত দেয়।',
    },
    source: 'Financial Gazette',
    category: 'Business',
    publishedDate: '2024-07-27T11:00:00Z',
  },
  {
    id: 'de-world-1',
    countryCode: 'DE',
    headline: 'Germany Pledges Aid for Global Climate Initiatives',
    summaries: {
      en: 'The German government has announced a significant financial pledge to support global initiatives tackling climate change.',
      bn: 'জার্মান সরকার জলবায়ু পরিবর্তন মোকাবিলায় বৈশ্বিক উদ্যোগগুলিকে সমর্থন করার জন্য একটি উল্লেখযোগ্য আর্থিক প্রতিশ্রুতি ঘোষণা করেছে।',
      de: 'Die Bundesregierung hat eine erhebliche finanzielle Zusage zur Unterstützung globaler Initiativen zur Bekämpfung des Klimawandels angekündigt.',
    },
    source: 'Berlin Nachrichten',
    category: 'World',
    publishedDate: '2024-07-26T16:00:00Z',
    originalImageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'us-science-1',
    countryCode: 'US',
    headline: 'Mars Rover Discovers Evidence of Ancient Microbial Life',
    summaries: {
      en: 'NASA\'s Mars rover has sent back data indicating strong evidence of ancient microbial life on the red planet.',
      bn: 'নাসার মার্স রোভার লাল গ্রহে প্রাচীন জীবাণু জীবনের শক্তিশালী প্রমাণ নির্দেশ করে ডেটা পাঠিয়েছে।',
    },
    source: 'Space Journal',
    category: 'Science',
    publishedDate: '2024-07-29T08:00:00Z',
  },
   {
    id: 'jp-tech-2',
    countryCode: 'JP',
    headline: 'Robotics Expo Showcases Future of Automation',
    summaries: {
      en: 'The annual Tokyo Robotics Expo featured cutting-edge automatons, from humanoid assistants to industrial manufacturing robots.',
      bn: 'বার্ষিক টোকিও রোবোটিক্স এক্সপোতে অত্যাধুনিক অটোমেটন প্রদর্শিত হয়েছে, যার মধ্যে হিউম্যানয়েড সহকারী থেকে শুরু করে শিল্প উত্পাদন রোবটও ছিল।',
      ja: '毎年恒例の東京ロボティクスエキスポでは、ヒューマノイドアシスタントから産業用製造ロボットまで、最先端のオートマトンが展示されました。',
    },
    source: 'Nikkei Tech',
    category: 'Technology',
    publishedDate: '2024-07-29T11:00:00Z',
    originalImageUrl: 'https://placehold.co/600x400.png',
  },
  {
    id: 'af-youtube-news-Jgzli-g24TU',
    countryCode: 'AF',
    headline: 'Afghanistan Daily News Update - July 23, 2024',
    summaries: {
      en: 'A video summary of key news events in Afghanistan for July 23, 2024. (Includes YouTube video link)',
      bn: '২৩শে জুলাই, ২০২৪ তারিখের আফগানিস্তানের গুরুত্বপূর্ণ খবরের ভিডিও সারাংশ। (ইউটিউব ভিডিও লিঙ্ক অন্তর্ভুক্ত)',
    },
    source: 'YouTube (News Source Unspecified)',
    category: 'General',
    publishedDate: '2024-07-23T12:00:00Z',
    videoUrl: 'https://youtu.be/Jgzli-g24TU?si=_WmN67oMHoihwz21',
    originalImageUrl: undefined,
  },
];
